# Variante recommandée via Microsoft Build of OpenJDK
FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu
EXPOSE 8089
ADD target/TimesheetDevopsApplication-ski-1.0.jar TimesheetDevopsApplication-ski-1.0.jar
ENTRYPOINT ["java","-jar","/TimesheetDevopsApplication-ski-1.0.jar"]
